# Generated by Django 4.0.5 on 2022-06-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingheadingchoices',
            name='belong_tomatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api.matchingheadingcollection'),
        ),
        migrations.AlterField(
            model_name='matchingheadingtext',
            name='belong_to_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='api.matchingheadingcollection'),
        ),
    ]
