# Generated by Django 4.0.5 on 2022-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_matchingheadingchoices_belong_tomatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingheadingtext',
            name='answer',
            field=models.CharField(max_length=1, null=True, verbose_name='Answer'),
        ),
    ]
