# Generated by Django 4.0.5 on 2022-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_matchingheadingtext_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingheadingtext',
            name='answer',
            field=models.CharField(max_length=4, null=True, verbose_name='Answer'),
        ),
    ]
