# Generated by Django 4.0.5 on 2022-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_matchingheadingtext_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Not Given', 'Not Given')], max_length=16, null=True)),
            ],
        ),
    ]
