# Generated by Django 4.0.5 on 2022-06-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paragraphmatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphmatching',
            name='belong_paragraph_matching',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='api.matchingheadingcollection'),
        ),
    ]
