# Generated by Django 4.0.5 on 2022-06-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_paragraphmatching_belong_paragraph_matching'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_completions', to='api.matchingheadingcollection')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_parts', to='api.summarycompletion')),
            ],
        ),
        migrations.CreateModel(
            name='GivenKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_letter', models.CharField(max_length=1, null=True)),
                ('key_descrp', models.CharField(max_length=255, null=True)),
                ('belong_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_choices', to='api.summarycompletion')),
            ],
        ),
    ]
