# Generated by Django 4.0.5 on 2022-06-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sentencepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('a_key', models.CharField(max_length=255, null=True)),
                ('b_key', models.CharField(max_length=255, null=True)),
                ('c_key', models.CharField(max_length=255, null=True)),
                ('d_key', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choices', to='api.matchingheadingcollection')),
            ],
        ),
    ]
