# Generated by Django 4.0.5 on 2022-06-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_matchingquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchingQuestion',
            new_name='MultipleChoice',
        ),
    ]
