# Generated by Django 4.0.5 on 2022-06-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_matchingquestion_multiplechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_selections', to='api.matchingheadingcollection')),
            ],
        ),
        migrations.CreateModel(
            name='ListSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_texts', to='api.wholelist')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('belong_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_choices', to='api.wholelist')),
            ],
        ),
    ]
