# Generated by Django 4.0.5 on 2022-06-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_wholelist_listsection_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('belong_coll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_sentences', to='api.matchingheadingcollection')),
            ],
        ),
        migrations.CreateModel(
            name='GivenPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_parts', to='api.matchingsentence')),
            ],
        ),
        migrations.CreateModel(
            name='ChoicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_descrp', models.CharField(max_length=255, null=True)),
                ('belong_sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_parts', to='api.matchingsentence')),
            ],
        ),
    ]
