# Generated by Django 4.0.5 on 2022-06-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_matchingsentence_givenpart_choicepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, null=True)),
                ('belong_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.matchingheadingcollection')),
            ],
        ),
        migrations.CreateModel(
            name='TablePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=64, null=True)),
                ('belong_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_parts', to='api.tablecompletion')),
            ],
        ),
        migrations.CreateModel(
            name='TableChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, null=True)),
                ('belong_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_choices', to='api.tablecompletion')),
            ],
        ),
    ]
